// vue/components/marketing/sections/contact-sections/simple_four_column.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div class="bg-white">
    <div class="mx-auto max-w-7xl py-24 px-4 sm:py-32 sm:px-6 lg:px-8">
      <h2 class="text-3xl font-bold tracking-tight text-gray-900">Our offices</h2>
      <p class="mt-6 max-w-3xl text-lg text-gray-500">Varius facilisi mauris sed sit. Non sed et duis dui leo, vulputate id malesuada non. Cras aliquet purus dui laoreet diam sed lacus, fames.</p>
      <div class="mt-10 grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-4">
        <div>
          <h3 class="text-lg font-medium text-gray-900">Los Angeles</h3>
          <p class="mt-2 text-base text-gray-500">
            <span class="block">4556 Brendan Ferry</span>
            <span class="block">Los Angeles, CA 90210</span>
          </p>
        </div>
        <div>
          <h3 class="text-lg font-medium text-gray-900">New York</h3>
          <p class="mt-2 text-base text-gray-500">
            <span class="block">886 Walter Streets</span>
            <span class="block">New York, NY 12345</span>
          </p>
        </div>
        <div>
          <h3 class="text-lg font-medium text-gray-900">Toronto</h3>
          <p class="mt-2 text-base text-gray-500">
            <span class="block">7363 Cynthia Pass</span>
            <span class="block">Toronto, ON N3Y 4H8</span>
          </p>
        </div>
        <div>
          <h3 class="text-lg font-medium text-gray-900">London</h3>
          <p class="mt-2 text-base text-gray-500">
            <span class="block">114 Cobble Lane</span>
            <span class="block">London N1 2EF</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

// react/components/marketing/sections/contact-sections/simple_four_column.jsx
/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
  return (
    <div className="bg-white">
      <div className="mx-auto max-w-7xl py-24 px-4 sm:py-32 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold tracking-tight text-gray-900">Our offices</h2>
        <p className="mt-6 max-w-3xl text-lg text-gray-500">
          Varius facilisi mauris sed sit. Non sed et duis dui leo, vulputate id malesuada non. Cras aliquet purus dui
          laoreet diam sed lacus, fames.
        </p>
        <div className="mt-10 grid grid-cols-1 gap-10 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <h3 className="text-lg font-medium text-gray-900">Los Angeles</h3>
            <p className="mt-2 text-base text-gray-500">
              <span className="block">4556 Brendan Ferry</span>
              <span className="block">Los Angeles, CA 90210</span>
            </p>
          </div>
          <div>
            <h3 className="text-lg font-medium text-gray-900">New York</h3>
            <p className="mt-2 text-base text-gray-500">
              <span className="block">886 Walter Streets</span>
              <span className="block">New York, NY 12345</span>
            </p>
          </div>
          <div>
            <h3 className="text-lg font-medium text-gray-900">Toronto</h3>
            <p className="mt-2 text-base text-gray-500">
              <span className="block">7363 Cynthia Pass</span>
              <span className="block">Toronto, ON N3Y 4H8</span>
            </p>
          </div>
          <div>
            <h3 className="text-lg font-medium text-gray-900">London</h3>
            <p className="mt-2 text-base text-gray-500">
              <span className="block">114 Cobble Lane</span>
              <span className="block">London N1 2EF</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
