// react/components/application-ui/layout/panels/card_with_gray_footer.jsx
/* This example requires Tailwind CSS v2.0+ */
export default function Example() {
  return (
    <div className="overflow-hidden rounded-lg bg-white shadow">
      <div className="px-4 py-5 sm:p-6">{/* Content goes here */}</div>
      <div className="bg-gray-50 px-4 py-4 sm:px-6">
        {/* Content goes here */}
        {/* We use less vertical padding on card footers at all sizes than on headers or body sections */}
      </div>
    </div>
  )
}

// vue/components/application-ui/layout/panels/card_with_gray_footer.vue
<!-- This example requires Tailwind CSS v2.0+ -->
<template>
  <div class="overflow-hidden rounded-lg bg-white shadow">
    <div class="px-4 py-5 sm:p-6">
      <!-- Content goes here -->
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <!-- Content goes here -->
      <!-- We use less vertical padding on card footers at all sizes than on headers or body sections -->
    </div>
  </div>
</template>
